routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::group(['middleware' => ['auth']], function () {
    Route::resource('parks', 'ParkController');
    Route::resource('account', 'AccountController');
    Route::resource('organisations', 'OrganisationController');
    Route::resource('partitions', 'PartitionController');
    Route::resource('records', 'RecordController');
    Route::resource('users', 'UserController');
    Route::resource('dash', 'DashController');
    Route::post('/partitions/{partition}/addImages/{}', 'PartitionController@addImages')->name('partitions.addImages');
});
Auth::routes(['verify' => true]);


Route::get('/here', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/search', 'ParkController@index')->name('search');

app/Record.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;


class Record extends Model implements HasMedia
{
    use HasMediaTrait;
    protected $fillable = [
        'report_year', 'season_id', 'partition_id', 'description'
    ];

    public function partition(){
        return $this->belongsTo('App\Partition');
    }

    public function season(){
        return $this->belongsTo('App\Season');
    }

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('small')
            ->width(150)
            ->height(150);
    }
}

app/Http/Controllers/RecordController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Partition;
use App\Record;
use App\Season;
use App\Park;
use App\Organisation;
use Illuminate\Support\Facades\Auth;
use Log;

class RecordController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $organisations = Organisation::all();
        
        if(Auth::user()->organisation_id == null){
            $records = Record::orderBy('id', 'DESC')->paginate(10);
        }else{
            $records = Record::where('partition_id', Auth::user()->organisation_id)->paginate(10);
        }
        
        return view('Record.recordIndex', compact('records', 'organisations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $records = Record::all();
        $seasons = Season::all();
        $redirected = false;

        Log::info('Check : ' . $request->get('partitionID'));

        if($request->has('partitionID')){
            $id = $request->get('partitionID');
            $partitions = Partition::find($id);
            $redirected = true;
        }else{
            if (Auth::user()->organisation_id != null){
                $park = Park::where('organisation_id', Auth::user()->organisation_id )->first(); 
                Log::info('Park Check : ' . $park);
                $partitions = Partition::where('park_id', $park->id)->get();
            }else{
                $partitions = Partition::all();
            }
        }
        $user = Auth::user();
        
        return view('Record.createRecord', compact('records', 'seasons', 'partitions', 'redirected'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Log::info('description check : ' . $request->get('description'));

        $request->validate([
            'description' => 'required|string',
            'season_id' => 'required',
            'partition_id' => 'required',
        ]);

            Log::info('Partition Check : ' . $request->get('partition_id'));

        $record = Record::firstOrNew([
            'report_year' => date("Y"),
            'description' => $request->get('description'),
            'season_id' => $request['season_id'],
            'partition_id' => $request->get('partition_id')
        ]);
        $record->save();

        if($request->hasFile('file1') && $request->file('file1')->isValid()){
            $record->addMediaFromRequest('file1')->toMediaCollection('report_images');
        }

        if($request->hasFile('file2') && $request->file('file2')->isValid()){
            $record->addMediaFromRequest('file2')->toMediaCollection('report_images');
        }

        if($request->hasFile('file3') && $request->file('file3')->isValid()){
            $record->addMediaFromRequest('file3')->toMediaCollection('report_images');
        }
        $record->save();

        return redirect('/records');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $record = Record::find($id);
        return view('Record.editRecord', compact('record'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'description' => 'required|string',
        ]);

        $record = Record::find($id);
        $record->description = $request->get('description');
        $record->save();

        if($request->hasFile('file1') && $request->file('file1')->isValid()){
            $record->addMediaFromRequest('file1')->toMediaCollection('report_images');
        }
        return redirect('/records')->with('updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $record = Record::find($id);
        $record->delete();
        return redirect('/records')->with('Deleted!');
    }
}

resources/views/Record/createRecord.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Add Record</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        @hasanyrole('Admin|Council')
            <form method="post" enctype="multipart/form-data" action="{{ route('records.store') }}">
                @csrf
                <br/>
                <br/>
                <div>
                    <label for="season">Season</label>
                    <select name="season_id">
                        @foreach ($seasons as $season )
                            <option value="{{$season->id}}">{{ $season->season}}</option>
                        @endforeach
                    </select>
                </div>
                <br/>
                @if($redirected == false)
                    <div>
                        <label for="partition">Partition</label>
                        <select name="partition_id">
                            @foreach ($partitions as $partition )
                                <option value="{{$partition->id}}">{{ $partition->name}}</option>
                            @endforeach
                        </select>
                    </div>
                @else
                    <label for="partition">Park Partition</label>
                    <label for="partition">{{$partitions->name}}</label>
                @endif
                <br/>
                <div class="form-group">
                    <label for="description">Description:</label>
                    <input type="text" class="form-control" name="description" />
                </div>
                <br/><br/>
                <input type="file" name="file1" />
                <br/><br/>
                <input type="file" name="file2" />
                <br/><br/>
                <input type="file" name="file3" />
                <br/><br/>
                <button type="submit" class="btn btn-secondary">Add Record</button>
            </form>
        @endhasanyrole
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/Record/editRecord.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Edit Record</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        @hasanyrole('Admin|Council')
            <form method="post" enctype="multipart/form-data" action="{{ route('records.update', $record->id)}}">
                @method('PATCH')
                @csrf
                <div class="form-group">
                    <label for="description">description:</label>
                    <input type="text" class="form-control" name="description" value="{{ $record->description }}">
                </div>

                <input type="file" name="file1" /> <br/><br/>
                <button type="submit" class="btn btn-secondary">Update</button>
            </form>
        @endhasanyrole
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/Record/recordIndex.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Records</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        @hasanyrole('Admin|Council')
            <table class="table table-striped"> 
                <thead>
                    <tr>
                        <th>Organisation</th>
                        <th>User</th>
                        <th>Park</th>
                        <th>Partition</th>
                        <th>Report Year</th>
                        <th>Season</th>
                        <th>Description</th>
                    </tr>
                </thead>
                @role('Admin')
                    <form method="POST" action="{{route('records.index')}}">
                        <select name="organisations" id="organisation">
                            @foreach ($organisations as $organisation)
                                <option value="{{$organisation->id}}">{{$organisation->name}}</option>
                            @endforeach
                        </select>
                    </form>
                @endrole
                <div><a style="margin: 19px;" enctype="multipart/form-data" href ="{{route('records.create') }}" class="btn btn-primary">New Report</a>
                    <tbody>
                        @foreach ($records as $record)
                            <tr>
                                <td>{{ $record->partition->park->organisation->name }} </td>
                                @if($record->partition->user != null)
                                    <td>{{ $record->partition->user->name }} </td>
                                @else
                                    <td>No User Assigned</td>
                                @endif
                                <td>{{ $record->partition->park->name }} </td>
                                <td><a href ="{{route('partitions.show', $record->partition->id) }}"> {{ $record->partition->name }} </a></td> 
                                <td>{{ $record->report_year }} </td>
                                <td>{{$record->season->season}}  </td>
                                <td>{{ $record->description }} </td>
                                <td><a href="{{route('records.edit', $record->id)}}" class="btn btn-primary">Edit</a></td>
                                <td><form action="{{route('records.destroy', $record->id)}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit"> Delete</button></form></td>       
                                @if($record->getMedia('report_images') != null)
                                    @foreach ($record->getMedia('report_images') as $image)
                                        <td> &nbsp;&nbsp;&nbsp;<a href="{{ $image->getUrl()}}"> <img src="{{ $image->getUrl('small') }}"> </a>  </td>
                                    @endforeach
                                @endif       
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                @endhasanyrole
    
                <div class="row">
                    <div class="col-12 d-flex justify-content-center pt-4">
                        {{$records->links()}}
                    </div>
                </div>
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection