routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::group(['middleware' => ['auth']], function () {
    Route::resource('parks', 'ParkController');
    Route::resource('account', 'AccountController');
    Route::resource('organisations', 'OrganisationController');
    Route::resource('partitions', 'PartitionController');
    Route::resource('records', 'RecordController');
    Route::resource('users', 'UserController');
    Route::resource('dash', 'DashController');
    Route::post('/partitions/{partition}/addImages/{}', 'PartitionController@addImages')->name('partitions.addImages');
});
Auth::routes(['verify' => true]);


Route::get('/here', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/search', 'ParkController@index')->name('search');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable implements HasMedia, MustVerifyEmail
{
    use Notifiable;
    use HasRoles;
    use HasMediaTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'address', 'contact_num', 'organisation_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')
            ->width(50)
            ->height(50);

        $this->addMediaConversion('square')
            ->width(280)
            ->height(312)
            ->sharpen(10);
    }


    public function partition()
    {
        return $this->hasOne('App\Partition');
    }

    public function organisation()
    {
        return $this->belongsTo('App\Organisation');
    }

    public static function last()
    {
        return static::all()->last();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Organisation;
use Log;
use Hash;
use App\Partition;
use Illuminate\Support\Facades\Auth;
use Illuminate\Pagination\Paginator;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Collection;

class UserController extends Controller
{

    public function paginate($items, $perPage = 5, $page = null, $options = [])
    {
    $page = $page ?: (Paginator::resolveCurrentPage() ?: 1);
    $items = $items instanceof Collection ? $items : Collection::make($items);
    return new LengthAwarePaginator($items->forPage($page, $perPage), $items->count(), $perPage, $page, $options);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $filter = $request->get('filter');
        $partitions = Partition::all();
        $assignedUsers = array();
        $unassignedUsers = array();
        $users = User::all();

        foreach($partitions as $partition){
            Log::info('Partition Id Check : ' . $partition);
            Log::info('user Id Check : ' . $partition->id);
            if($partition->user_id !=null){
                array_push($assignedUsers, $partition->user); 
            }
        }
        foreach($users as $user){
            if(Auth::user()->roles->first()->name == 'Citizen'){
                if(! in_array($user, $assignedUsers)){
                    array_push($unassignedUsers, $user);
                }
            }
        }//for

        if ($filter == 'all'|| $filter == null){
            $users = User::orderBy('id', 'DESC')->paginate(10);
        }else if($filter == 'reg'){
            if($assignedUsers != null){
                $users = $this->paginate($assignedUsers);
            }else{
                $users = null;
            }
        }else if($filter == 'noReg'){
            if($unassignedUsers != null){
                $users = $this->paginate($unassignedUsers);
            }else{
                $users = null;
            }
        }//else
        return view('User.userIndex', compact('users', 'filter',));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       $users = User::all();
       $organisations = Organisation::all();

       return view('User.createUser', compact('users', 'organisations'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|max:255',
            'password' => 'required|string|min:8',
            'address' => 'required|string|min:5',
            'contact_num' => 'required|numeric|min:11',
            'organisation_id' => 'nullable|numeric',
        ]);
        $user = User::firstOrNew([
            'email' => $request['email'],
        ]);
        Log::info('Address Check : ' . $request->get('address'));

        $user->fill([
            'name' => $request->name,
            'address' => $request->address,
            'contact_num' => $request->contact_num,
            'organisation_id' => $request->organisation_id,
            'password' => Hash::make($request->password),
            ]);
            $user->save();

        return redirect('/users')->with('User added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        $organisations = Organisation::all();
 
        return view('User.editUser', compact('user', 'organisations'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|max:255',
            'password' => 'required|string|min:8',
            'address' => 'required|string|min:10',
            'contact_num' => 'required|numeric|min:11',
            'organisation_id' => 'nullable|numeric',
        ]);

        $user = User::find($id);
        $user->name = $request->get('name');
        $user->email = $request->get('email');
        $user->address = $request->get('address');
        $user->contact_num = $request->get('contact_num');
        $user->organisation_id = $request->get('organisation_id');
        $user->save();

        //Role

        $user->assignRole($request->input('roles')); 
        return redirect('/users')->with('updated user');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();

        return redirect('/users')->with('User deleted!');
    }
}

resources/views/User/createUser.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Create User</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        

        @role('Admin')
            <form method="post" action="{{ route('users.store') }}">
                @csrf
                <div class="form-group">
                    <label for="name">name:</label>
                    <input type="text" class="form-control" name="name" />
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" class="form-control" name="email"/>
                </div>
                <div class="form-group">
                    <label for=password>Password</label>
                    <input type="password" class="form-control" name="password"/>
                <div>
                    <label for="contactNumber">Contact Number</label>
                    <input type="string" class="form-control" name="contact_num"/>
                </div>
                <div>
                    <label for="address">Address</label>
                    <input type="string" class="form-control" name="address"/>
                </div>
                <br/><br/>
                <div>
                    <label for="organisation">Organisation</label>
                    <select name="organisation_id">
                        @foreach ($organisations as $organisation )
                            <option value="{{$organisation->id}}">{{ $organisation->name}}</option>
                        @endforeach
                    </select>
                </div>
                <button type="submit" class="btn btn-secondary">Add User</button>
            </form>
        @endrole
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/User/editUser.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Edit User</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        @role('Admin')
            <form method="post" action="{{ route('users.update', $user->id)}}">
                @method('PATCH')
                @csrf
                <div class="form-group">
                    <label for="name">name:</label>
                    <input type="text" class="form-control" name="name" value="{{ $user->name }}">
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" class="form-control" name="email" value="{{$user->email}}">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" name="password" value="{{$user->password}}">
                </div>
                <div class="form-group">
                    <label for="address">address:</label>
                    <input type="text" class="form-control" name="address" value="{{ $user->address }}">
                </div>
                <div class="form-group">
                    <label for="contact_num">Contact Number:</label>
                    <input type="text" class="form-control" name="contact_num" value="{{ $user->contact_num }}">
                </div>
                <div class="form-group">
                    <label for="organisation">Organisation:</label>
                    <select name="organisation_id">
                        @foreach ($organisations as $organisation)
                            <option value="{{$organisation->id}}">{{ $organisation->name }}</option>
                        @endforeach
                    </select>
                </div>
                <button type="submit" class="btn btn-secondary">Update</button>
            </form>
        @endrole
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/User/userIndex.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Users</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        <div><a style="margin: 19px;" href ="{{ route('users.create') }}" class="btn btn-primary">New User</a>
            <a style="margin: 19px;" href="{{ route('users.index', ['filter'=> 'all']) }}" class="btn btn-primary">All Users</a>
            <a style="margin: 19px;" href="{{ route('users.index', ['filter'=> 'reg']) }}" class="btn btn-primary">Assigned Users </a>
            <a style="margin: 19px;" href="{{ route('users.index', ['filter'=> 'noReg']) }}" class="btn btn-primary">Unassigned Users </a></div>
        @role('Admin')
            @if($users != null)
                <table class="table table-striped"> 
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Contact Number</th>
                            <th>Address</th>
                            <th>Organisation</th>
                            <th>Park</th>
                            <th>Partition</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($users as $user)
                            <tr>
                                <td>{{ $user->name }} </td>
                                <td>{{ $user->email }} </td>
                                <td>{{ $user->contact_num }} </td>
                                <td>{{ $user->address }} </td>
                                
                                @if($user->organisation != null)
                                    <td>{{$user->organisation->name}} </td>
                                @else
                                    <td>No Organisation</td>
                                @endif

                                @if($user->partition != null && $user->organisation !=null)
                                    <td>{{ $user->partition->park->name }}  </td> 
                                    <td>{{ $user->partition->name }}  </td> 
                                @else
                                    <td>N/A</td>
                                    <td>N/A</td>
                                @endif
                                
                                <td><a href="{{route('users.edit', $user->id)}}" class="btn btn-primary">Edit</a></td>
                                <td><form action="{{route('users.destroy', $user->id)}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit"> Delete</button></form></td>                           
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @endif
        @endrole
        @if($users != null)
            <div class="row">
                <div class="col-12 d-flex justify-content-center pt-4">
                   {{$users->links() }}
                </div>
            </div>
        @else
            <h3>No users matching criteria</h3>
        @endif
            @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
            @endif
        </div>
    </div>
</div>
@endsection