routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::group(['middleware' => ['auth']], function () {
    Route::resource('parks', 'ParkController');
    Route::resource('account', 'AccountController');
    Route::resource('organisations', 'OrganisationController');
    Route::resource('partitions', 'PartitionController');
    Route::resource('records', 'RecordController');
    Route::resource('users', 'UserController');
    Route::resource('dash', 'DashController');
    Route::post('/partitions/{partition}/addImages/{}', 'PartitionController@addImages')->name('partitions.addImages');
});
Auth::routes(['verify' => true]);


Route::get('/here', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/search', 'ParkController@index')->name('search');

app/Park.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;

class Park extends Model implements HasMedia
{
    use HasMediaTrait;
    
    protected $fillable = [
        'name', 'organisation_id',
    ];

    public function organisation(){
        return $this->belongsTo('App\Organisation');
    }

    public function partition(){
        return $this->hasMany('App\Partition');
    }

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')
            ->width(50)
            ->height(50);
           
        $this->addMediaConversion('small')
            ->width(150)
            ->height(150);
    }
}

app/Http/Controllers/ParkController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Park;
use App\Organisation;
use App\Partition;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Auth;
use Illuminate\Pagination\Paginator;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Collection;


class parkController extends Controller
{

    public function paginate($items, $perPage = 5, $page = null, $options = [])
    {
    $page = $page ?: (Paginator::resolveCurrentPage() ?: 1);
    $items = $items instanceof Collection ? $items : Collection::make($items);
    return new LengthAwarePaginator($items->forPage($page, $perPage), $items->count(), $perPage, $page, $options);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $filter = $request->get('filter');
        $partitions = Partition::all();
        $unassignedparks = array();
        $fullyAssignedparks = array();
        $empty = 'Not Empty';

        if($request->has('q')){
            Log::info('Query Check : ' . $request->get('q'));
            $q = $request->get( 'q' );
            Log::info('Query Check : ' . $q);
            $parks = Park::where('name', 'LIKE', '%' . $q . '%')->get();
            Log::info('Parks Array : ' . $parks);
            if (count ( $parks ) > 0) {
                $parks = $this->paginate($parks);
            }else{
                $parks = Park::paginate(5);
                $empty = null;
            }
        }else {
            if($filter == null || $filter == 'all'){
                Log::info('data');
                if(Auth::user()->organisation_id != null){
                    $parks = Park::where('organisation_id', Auth::user()->organisation_id)->orderBy('organisation_id', 'DESC')->paginate(10);
                }else{
                    $parks = Park::paginate(5);
                }

            }else if($filter = 'assigned'){
                $parks = Park::all();
                foreach($partitions as $partition){
                    Log::info('Data' );
                    if($partition->user == null){
                        Log::info('Check UnAssigned Array Element' . $partition);
                        $parksWithUnassignedPartitions = $partition->park_id;
                        $unassignedpark = Park::where('id', $parksWithUnassignedPartitions)->first();
                        array_push($unassignedparks, $unassignedpark);
                    }//if
                }// foreach
                foreach($parks as $park){
                    $bool = false;
                    foreach($unassignedparks as $unassigned){
                        if($park->id == $unassigned->id){
                            $bool = true;
                            Log::info('Check');
                            break;
                        }//if
                    }//foreach
                    if(! $bool){
                        if(Auth::user()->organisation_id !=null){
                            $park = Park::where('organisation_id', Auth::user()->organisation_id)->first();
                            array_push($fullyAssignedparks, $park);
                        }else{
                            array_push($fullyAssignedparks, $park);
                        }//if
                    }//if
                }//foreach

                if(count($fullyAssignedparks) > 0){
                    $parks = $this->paginate($fullyAssignedparks);
                }else{
                    $parks = Park::all();
                    $empty = null;
                }
            }
        }//if
        return view('Park.parkIndex', compact('parks', 'empty', 'parks'));    
    }//class

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Auth::user()->organisation_id != null){
            $parks = Park::all();
            $organisations = Organisation::where('id', Auth::user()->organisation_id)->get();
        }else{
            $parks = Park::all();
            $organisations = Organisation::all();
        }
        return view('Park.createPark', compact('parks', 'organisations'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'organisation_id' => 'required',
        ]);

        $park = park::firstOrNew([
            'name' => $request->name,
            'organisation_id' => $request->organisation_id,
        ]);
        $park->save();


        if($request->hasFile('file1') && $request->file('file1')->isValid()){
            $park->addMediaFromRequest('file1')->toMediaCollection('park_images');
        }

        if($request->hasFile('file2') && $request->file('file2')->isValid()){
            $park->addMediaFromRequest('file2')->toMediaCollection('park_images');
        }

        if($request->hasFile('file3') && $request->file('file3')->isValid()){
            $park->addMediaFromRequest('file3')->toMediaCollection('park_images');
        }


        return redirect('/parks')->with('Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $park = Park::find($id);
        $organisations = Organisation::all();
 
        return view('Park.editPark', compact('park', 'organisations'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'organisation_id' => 'required|numeric',
        ]);

        $park = Park::find($id);
        $park->name = $request->get('name');
        $park->organisation_id = $request->get('organisation_id');
        $park->save();
        $parkMedia = $park->getMedia('park_images');

        if($request->hasFile('file1') && $request->file('file1')->isValid()){
            $park->addMediaFromRequest('file1')->toMediaCollection('park_images');
        }

        return redirect('/parks')->with('Updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $park = Park::find($id);
        $park->delete();

        return redirect('/parks')->with('park deleted!');
    }

    public function deleteImage($id, Request $request){


        return redirect('/parks')->with('deleted!');
    }
}

resources/views/Park/createPark.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Add park</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        @hasanyrole('Admin|Council')
            <form method="post" enctype="multipart/form-data" action="{{ route('parks.store') }}">
                @csrf
                <div class="form-group">
                    <label for="name">name:</label>
                    <input type="text" class="form-control" name="name" />
                </div>
                <div>
                    <label for="organisation">Organisation</label>
                    <select name="organisation_id">
                        @foreach ($organisations as $organisation )
                            <option value="{{$organisation->id}}">{{ $organisation->name}}</option>
                        @endforeach
                    </select>
                </div>
                <br/>
                <input type="file" name="file1" />
                <br/><br/>
                <input type="file" name="file2" />
                <br/><br/>
                <input type="file" name="file3" />
                <br/><br/>
                <button type="submit" class="btn btn-secondary">Add park</button>
            </form>
        @endhasanyrole
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/Park/editPark.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Edit park</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        @hasanyrole('Admin|Council')
            <form method="post" enctype="multipart/form-data" action="{{ route('parks.update', $park->id)}}">
                @method('PATCH')
                @csrf
                <div class="form-group">
                    <label for="name">name:</label>
                    <input type="text" class="form-control" name="name" value="{{ $park->name }}">
                </div>
                <div class="form-group">
                    <label for="organisation">Organisation:</label>
                    <select name="organisation_id">
                        @foreach ($organisations as $organisation)
                            <option value="{{$organisation->id}}">{{ $organisation->name }}</option>
                        @endforeach
                    </select>
                </div>
                    <input type="file" name="file1" />
                <button type="submit" class="btn btn-secondary">Update</button>
            </form>
        @endhasanyrole
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/Park/parkIndex.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Parks</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        <div>   
            @role('Admin')
                <form class="form-inline" action="/search" method="POST" role="search" >
                    {{ csrf_field() }}
                    <div class="input-group">
                        <input type="text" name="q" width="500px"
                            placeholder="Search Parks by Name"> <span class="input-group-btn">&nbsp;&nbsp;&nbsp;
                            <button type="submit" class="btn btn-primary">Search</button>
                        </span>
                    </div>
                </form>
            @endrole
           
            @hasanyrole('Admin|Council')
                <a style="margin:19px;" href="{{route('parks.create')}}" class="btn btn-primary">Create Park</a>
                <a style="margin: 19px;" href ="{{ route('partitions.create') }}" class="btn btn-primary">Create Partition</a>
                <a style="margin: 19px;" href="{{ route('parks.index', ['filter'=> 'all']) }}" class="btn btn-primary">All Parks</a>
                <a style="margin: 19px;" href="{{ route('parks.index', ['filter'=> 'assigned']) }}" class="btn btn-primary">Assigned parks</a>
            @endhasanyrole
            <a href="{{route('partitions.index')}}" class="btn btn-primary">Show Partitions</a>

        </div>
        
            <table>
                <thead>
                    <tr>
                        <th>Park Name</th>
                        <th>Organisation</th>
                    </tr>
                </thead> 
               
                <tbody>
                    @if($empty != null)
                        @foreach ($parks as $park)
                            <tr>
                                <td>{{ $park->name }}</td>
                                <td>&nbsp;&nbsp;&nbsp;{{ $park->organisation->name }}</td>
                                @hasanyrole('Admin|Council')
                                    <td>&nbsp;&nbsp;&nbsp;<a href="{{route('parks.edit', $park->id)}}" class="btn btn-primary">Edit</a></td>
                                    <td><form action="{{route('parks.destroy', $park->id)}}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    &nbsp;&nbsp;&nbsp;<button class="btn btn-primary" type="sumbit"> Delete</button></form></td>
                                    @if($park->getMedia('park_images') != null)
                                        @foreach ($park->getMedia('park_images') as $image)
                                            <td> &nbsp;&nbsp;&nbsp;<a href="{{ $image->getUrl()}}"> <img src="{{ $image->getUrl('small') }}"> </a>  </td>
                                        @endforeach
                                    @endif
                                @endhasanyrole
                            </tr> 
                        @endforeach
                    @else
                            <h3>No parks matching criteria</h3>
                    @endif
                </tbody>
            </table>
                <div class="row">
                    <div class="col-12 d-flex justify-content-center pt-4">
                        {{$parks->links()}}
                    </div>
                </div>
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection