routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::group(['middleware' => ['auth']], function () {
    Route::resource('parks', 'ParkController');
    Route::resource('account', 'AccountController');
    Route::resource('organisations', 'OrganisationController');
    Route::resource('partitions', 'PartitionController');
    Route::resource('records', 'RecordController');
    Route::resource('users', 'UserController');
    Route::resource('dash', 'DashController');
    Route::post('/partitions/{partition}/addImages/{}', 'PartitionController@addImages')->name('partitions.addImages');
});
Auth::routes(['verify' => true]);


Route::get('/here', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/search', 'ParkController@index')->name('search');

app/Partition.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;

class Partition extends Model implements HasMedia
{
    protected $fillable = [
        'name', 'park_id', 'user_id', 'days_council_service_end',
    ];

    use HasMediaTrait;
    
    public function park(){
        return $this->belongsTo('App\Park');
    }

    public function user(){
        return $this->belongsTo('App\User');
    }

    public function record() {
        return $this->hasOne('App\Record');
    }

    public function registerMediaConversions(Media $media = null)
    {
           
        $this->addMediaConversion('small')
            ->width(150)
            ->height(150);
    }
}

app/Http/Controllers/PartitionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Partition;
use App\Park;
use App\User;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Builder;

class PartitionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $filter = $request->get('filter');
        $partitions = Partition::all();

        
        if($filter == 'all'|| $filter == null){
            Log::info('Check : ');

            if(Auth::user()->roles->first()->name == 'Admin'){
                Log::info('Check : ');
                $partitions = Partition::all();

            }else if(Auth::user()->roles->first()->name == 'Council'){


                $parks= Park::where('organisation_id', Auth::user()->organisation_id)->get();
                $councilArray = array();
                foreach($parks as $park){
                    Log::info('Park Check : ' . $park);
                    $councilPartitions = Partition::where('park_id', $park->id)->get();
                    Log::info('councilPartitions : ' . $councilPartitions);

                    foreach($councilPartitions as $partition){
                        array_push($councilArray, $partition);
                    }
                }
                Log::info(print_r($councilArray, true));

                if(count($councilArray) > 0){
                    $partitions = $councilArray;
                }else{
                    $partitions = null;
                }

            }else if(Auth::user()->roles->first()->name == 'Citizen'){
                $citizenArray = array();
                foreach($partitions as $partition){
                    if($partition->user_id == Auth::user()->id){
                        array_push($citizenArray, $partition);
                    }
                }
                if(count($citizenArray) > 0){
                    $partitions = $citizenArray;
                }else{
                    $partitions = null;
                }
                Log::info(print_r($partitions, true));
            }
        }else if($filter == 'due'){
            if(Auth::user()->organisation_id != null){
                $parks= Park::where('organisation_id', Auth::user()->organisation_id)->get();
            }else{
                $parks= Park::all();
            }
            $duePartitionsArray = array();
                foreach($parks as $park){
                    $duepartitions = Partition::where('park_id', $park->id)->where('days_council_service_end', '<=', 30)->get();
                    foreach($duepartitions as $partition){
                        array_push($duePartitionsArray, $partition );
                    }//for
                }//for

            if(count($duePartitionsArray) > 0){
                $partitions = $duePartitionsArray;
            }else{
                $partitions = null;
            }

        }else if($filter == 'unassigned'){
            $unassignedPartitions = array();
            if(Auth::user()->roles->first()->name == 'Admin'){
                foreach($partitions as $partition){
                    if($partition->user_id == null){
                        array_push($unassignedPartitions, $partition);
                    }
                }// foreach
            }else {
                $parks= Park::where('organisation_id', Auth::user()->organisation_id)->get();
                foreach($parks as $park){
                    $unassigned = Partition::where('park_id', $park->id)->get();
                    foreach($unassigned as $partition){
                        if($partition->user_id == null){
                            array_push($unassignedPartitions, $partition );
                        }
                    }//for
                }//for
            }
            $partitions = $unassignedPartitions;
        }
        return view('Partition.partitionIndex', compact('partitions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $partition = Partition::all();
        if(Auth::user()->organisation_id != null){
        $parks = Park::where('organisation_id', Auth::user()->organisation_id)->get();
        }else{
            $parks = Park::all();
        }
        
        return view('Partition.createPartition', compact('partition', 'parks'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            ]);

            $partition = Partition::firstOrNew([
                'name' => $request->name,
                'park_id' => $request->park_id,
            ]);
            $partition->save();

            if($request->hasFile('file1') && $request->file('file1')->isValid()){
                $partition->addMediaFromRequest('file1')->toMediaCollection('partition_images');
            }
    
            if($request->hasFile('file2') && $request->file('file2')->isValid()){
                $partition->addMediaFromRequest('file2')->toMediaCollection('partition_images');
            }
    
            if($request->hasFile('file3') && $request->file('file3')->isValid()){
                $partition->addMediaFromRequest('file3')->toMediaCollection('partition_images');
            }
            $partition->save();
            return redirect('/parks')->with('Added');
        }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $partition = Partition::find($id);
        return view('Partition.showPartition', compact('partition'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $partition = Partition::find($id);
        if(Auth::user()->organisation_id == null){
            //Give Citizens not Assigned
            $users = User::whereHas("roles", function(Builder $q) { $q->where("name", "Citizen"); })->get();

        }else{
            //give citizens from org ID
            $users = User::whereHas("roles", function(Builder $q) {
             $q->where("name", "Citizen")->where('organisation_id', Auth::user()->organisation_id); })->get();
        }
        return view('Partition.editPartition', compact('users', 'partition'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $partition = Partition::find($id);
        if($request->has('user_id')){
            Log::info('Check');
            $partitions = Partition::all();

            foreach($partitions as $p){
                if($p->user_id == $request->get('user_id')){
                    $p->user_id = null;
                    $p->save();
                }
            }
            $partition->user_id =  $request->get('user_id');
            $partition->days_council_service_end =  $request->get('days');
        }else{
            Log::info('Data');
            if($request->hasFile('file1') && $request->file('file1')->isValid()){
                $partition->addMediaFromRequest('file1')->toMediaCollection('partition_images');
            }
    
            if($request->hasFile('file2') && $request->file('file2')->isValid()){
                $partition->addMediaFromRequest('file2')->toMediaCollection('partition_images');
            }
    
            if($request->hasFile('file3') && $request->file('file3')->isValid()){
                $partition->addMediaFromRequest('file3')->toMediaCollection('partition_images');
            }
        }
        $partition->save();
        return redirect('/partitions')->with('Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $partition = Partition::find($id);
        $partition->delete();

        return redirect('/parks')->with('Deleted!');
    }

    public function addImages($id, Request $request)
    {
        Log::info("Entered here");
        $partition = Partition::find($id);
        if($request->hasFile('file1') && $request->file('file1')->isValid()){
            $partition->addMediaFromRequest('file1')->toMediaCollection('partition_images');
        }

        if($request->hasFile('file2') && $request->file('file2')->isValid()){
            $partition->addMediaFromRequest('file2')->toMediaCollection('partition_images');
        }

        if($request->hasFile('file3') && $request->file('file3')->isValid()){
            $partition->addMediaFromRequest('file3')->toMediaCollection('partition_images');
        }
        $partition->save();
        return redirect('/parks')->with('Added');
    }


/*
 
*/

}

resources/views/Partition/createPartition.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Create Partition</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        @hasanyrole('Admin|Council')
            <form method="post" enctype="multipart/form-data" action="{{ route('partitions.store') }}">
                @csrf
                <div class="form-group">
                    <label for="name">name:</label>
                    <input type="text" class="form-control" name="name" />
                </div>
                <div>
                    <label for="park">park</label>
                    <select name="park_id">
                        @foreach ($parks as $park )
                            <option value="{{$park->id}}">{{ $park->name}}</option>
                        @endforeach
                    </select>
                </div>
                <br/><input type="file" name="file1" /><br/><br/>
                <input type="file" name="file2" /><br/><br/>
                <input type="file" name="file3" /><br/><br/>
                <button type="submit" class="btn btn-secondary">Add Zone</button>
            </form>
        @endhasanyrole
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/Partition/editPartition.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Assign User</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        @hasanyrole('Admin|Council')
            <form method="post" enctype="multipart/form-data" action="{{ route('partitions.update', $partition->id)}}">
                @method('PATCH')
                @csrf
                <div class="form-group">
                    <label for="user">User:</label>
                    @if($users != null)
                        <select name="user_id">
                            @foreach ($users as $user)
                                <option value="{{$user->id}}">{{ $user->name }}</option>
                            @endforeach
                        </select>
                    @else
                        <h3>No Available Users</h3>
                    @endif
                </div>

                <div class="form-group">
                    <label for="days">Days Left:</label>
                    <input type="number" class="form-control" name="days" value="{{ $partition->days_council_service_end }}">
                </div>
                <button type="submit" class="btn btn-secondary">Update</button>
            </form>
        @endhasanyrole
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/Partition/partitionIndex.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Partition</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
        @endif
        @hasanyrole('Admin|Council')
            <a style="margin: 19px;" href="{{ route('partitions.index', ['filter'=> 'all']) }}" class="btn btn-primary">All</a>
            <a style="margin: 19px;" href="{{ route('partitions.index', ['filter'=> 'due']) }}" class="btn btn-primary">Due Soon</a>
            <a style="margin: 19px;" href="{{ route('partitions.index', ['filter'=> 'unassigned']) }}" class="btn btn-primary">Unassigned</a>
        @endhasanyrole
        @if($partitions == null)
            <h1>No Partitions matching criteria</h1>
        @else
            <table>
                <thead>
                    <tr>
                        <th>Partition</th>
                        <th>Park</th>
                        <th>Organisation</th>
                        <th>User</th>
                        <th>Days Left</th>
                        
                    </tr>
                </thead>
                <tbody>
                    @foreach ($partitions as $partition )
                        <tr>
                            <td>{{$partition->name }}</td> 
                            <td>{{$partition->park->name }}</td>
                            <td>{{$partition->park->organisation->name }}</td>
                            @if($partition->user_id != null)
                                <td>{{$partition->user->name }}</td>
                                <td>{{$partition->days_council_service_end}}</td>
                            @else
                                <td>No User is looking after this Zone</td>
                                <td>N/A</td>
                            @endif
                            
                            @hasanyrole('Admin|Council')
                            <div>
                                <td><a href="{{route('partitions.edit', $partition->id)}}" class="btn btn-primary">Assign</a></td>
                                <td><a href="{{route('partitions.show', $partition->id)}}" class="btn btn-primary">Show</a></td>
                                <td><form action="{{route('partitions.destroy', $partition->id)}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-primary" type="sumbit"> Delete</button></form></td>
                            @endhasanyrole
                            </div>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @endif
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        </div>
    </div>
</div>
@endsection

resources/views/Partition/showPartition.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Partition Details</h1>
        <div>
        @if ($errors->any())
            <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
            </div><br/>
            @endif
            <br/>
            <a class="btn btn-primary" href="{{route('records.create', ['partitionID'=>$partition->id])}}">Create Record</a>
            <br/><br/>
            <table>
                <thead>
                    <tr>
                        <th>Partition</th>
                        <th>Park</th>
                        <th>Organisation</th>
                        <th>User</th>
                        <th>Days Left&nbsp;&nbsp;&nbsp;&nbsp;</th>
                        <th>Images</th>
                    </tr>
                </thead>

                <tbody>
                    <tr>
                        <td>&nbsp;&nbsp;{{$partition->name }}</td> 
                        <td>&nbsp;&nbsp;{{$partition->park->name }}</td>
                        <td>&nbsp;&nbsp;{{$partition->park->organisation->name }}</td>
                        @if($partition->user_id != null)
                            <td>&nbsp;&nbsp;{{$partition->user->name }}</td>
                            <td>&nbsp;&nbsp;{{$partition->days_council_service_end}}</td>
                        @else
                            <td>&nbsp;&nbsp;No User is looking after this Zone</td>
                            <td>&nbsp;&nbsp;N/A</td>
                        @endif    
                    </tr>
                </tbody>
            </table>
            @if($partition->getMedia('partition_images') != null)
                @foreach ($partition->getMedia('partition_images') as $image)
                    <td> &nbsp;&nbsp;&nbsp;<a href="{{ $image->getUrl()}}"> <img src="{{ $image->getUrl('small') }}"> </a>  </td>
                @endforeach
            @else
                    <h4>No Images</h4>
            @endif
            <br/>
            <br/>
            <h3>Add Images</h3>
            <form method="post" enctype="multipart/form-data" action="{{ route('partitions.update', $partition->id)}}">
                @csrf
                <br/><input type="file" name="file1" /><br/>
                <input type="file" name="file2" /><br/>
                <input type="file" name="file3" /><br/>
                <button type="submit" class="btn btn-secondary">Add Images</button>
            </form>
        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    </div>
</div>
</div>
@endsection